Repository nhn-academy/eggplant-delivery-schedule, pull requests merged in 2022-08, with the labels that each got.

#7 Rabbit Mq 설정
  pom.xml
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/RabbitmqConfig.java
  src/main/resources/application.yml
Labels: feat, chore

#10 entity 작성
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/status/Status.java
  src/main/resources/application.yml
Labels: feat

#13 feat: Writer, Reader 수정, 배송 위치 변경 Job, Step 틀 구현
  pom.xml
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/EggplantDeliveryScheduleApplication.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/DeliveryInfoStatusAdaptor.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/impl/DeliveryInfoStatusAdaptorImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/DataSourceConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/BatchConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/JobConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/StepConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/job/DeliveryStatusChangeStepConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/ChangedDeliveryInfoDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/response/SecureKeyResponseDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/Location.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/status/Status.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/exception/CustomJobException.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/exception/NotFoundDeliveryInfoException.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/processor/DeliveryInfoStatusTargetProcessor.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/LocationChangeReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/PrepareDeliveryStatusReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/ReadyToDeliveringReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/CustomDeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/LocationRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/scheduler/DeliveryInfoStatusScheduler.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/service/DeliveryInfoService.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/service/impl/DefaultDeliveryInfoService.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/LocationChangeWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/PrepareDeliveryStatusWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/ReadyToDeliveringWriter.java
  src/main/resources/application.yml
Labels: feat

#16 잘못된 layer 삭제
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/ReadyToDeliveringReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/service/DeliveryInfoService.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/service/impl/DefaultDeliveryInfoService.java
Labels: fix

#21 test: repository 테스트 추가
  pom.xml
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/JobConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/StepConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/status/writer/DeliveringToArrivalWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/status/writer/DeliveryLocationChangeWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/status/writer/ReadyToDeliveringWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/exception/CustomJobException.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/LocationChangeReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/LocationChangeWriter.java
  src/test/java/com/nhnacademy/eggplantdeliveryschedule/EggplantDeliveryScheduleApplicationTests.java
  src/test/java/com/nhnacademy/eggplantdeliveryschedule/repository/CustomDeliveryInfoRepositoryTest.java
Labels: test

#23 JavaDocs 추가
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/EggplantDeliveryScheduleApplication.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/DeliveryInfoStatusAdaptor.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/impl/DeliveryInfoStatusAdaptorImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/DataSourceConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/BatchConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/JobConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/batch/StepConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/ChangedDeliveryInfoDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/response/SecureKeyResponseDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/exception/CustomJobException.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/exception/NotFoundDeliveryInfoException.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/DeliveringToArrivalReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/DeliveryLocationChangeReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/ReadyToDeliveringReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/CustomDeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/repository/LocationRepository.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/scheduler/DeliveryScheduler.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/DeliveringToArrivalWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/DeliveryLocationChangeWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/ReadyToDeliveringWriter.java
  src/test/java/com/nhnacademy/eggplantdeliveryschedule/repository/CustomDeliveryInfoRepositoryTest.java
Labels: docs

#26 feat: github action CD 구축
  .github/workflows/maven.yml
  pom.xml
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/DeliveringToArrivalReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/DeliveryLocationChangeReader.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/reader/ReadyToDeliveringReader.java
  src/main/resources/application.yml
Labels: feat

#28 feat: Queue 설정 수정
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/DeliveryInfoStatusAdaptor.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/adaptor/impl/DeliveryInfoStatusAdaptorImpl.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/constant/ExchangeConstant.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/constant/RoutingKeyConstant.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/ChangedDeliveryInfoDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/DeliveringToArrivalWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/ReadyToDeliveringWriter.java
Labels: feat, fix

#30 chore: 배송 상태 변경 스케줄 시간 변경
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/scheduler/DeliveryScheduler.java
Labels: chore

#31 chore: 시간초 변경
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/scheduler/DeliveryScheduler.java
Labels: chore

#35 feat: 배송상태 변경시 쇼핑몰 서버에 전달하기 위한 작업
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/scheduler/DeliveryScheduler.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/DeliveringToArrivalWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/DeliveryLocationChangeWriter.java
  src/main/java/com/nhnacademy/eggplantdeliveryschedule/writer/ReadyToDeliveringWriter.java
Labels: feat
